version: "3"

services:
  #node/react application
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: node_server
    restart: unless-stopped
  
  #nginx web server
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    restart: unless-stopped
    depends_on:
      - node_server
  #lets encrypt 
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot  --email alexhong681@gmail.com --agree-tos --no-eff-email --staging -d 157.245.228.173

volumes:
  certbot-etc:
  certbot-var:
