version: "3.7"

services:
  #node/react application
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: node_server
    restart: always
    depends_on:
      - redis

  #redis cache
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    restart: always
  
  #nginx web server
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs:/etc/ssl/certs
    container_name: nginx
    restart: always
    depends_on:
      - node_server  
