apiVersion: v1
kind: Service
metadata:
    name: sfpayroll-service
spec:
    # TODO change to LoadBalancer type when deployed to cloud server
    type: NodePort
    ports:
        - protocol: TCP
          nodePort: 30000
          port: 80
          targetPort: 4000
    selector:
        app: sfpayroll-deployment
